In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

# Load the model
model = keras.models.load_model("simple_4_model.h5")

# Print model summary
model.summary()

# Access weights for each layer
for i, layer in enumerate(model.layers):
    print(f"\n--- Layer {i}: {layer.name} ({layer.__class__.__name__}) ---")
    weights = layer.get_weights()
    
    if weights:
        for j, w in enumerate(weights):
            print(f"Weight matrix {j} shape: {w.shape}")
            print(f"Weight matrix {j}:\n{w}")
    else:
        print("No weights in this layer")

# Access specific layer weights by index or name
first_layer_weights = model.layers[0].get_weights()
print(f"\nFirst layer weights: {first_layer_weights}")

# Get weights as a list of numpy arrays for all layers
all_weights = model.get_weights()
print(f"\nTotal number of weight arrays: {len(all_weights)}")

Model: "sequential_49"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_183 (Dense)               │ (None, 4)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_134 (Dropout)           │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_184 (Dense)               │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19 (80.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)


--- Layer 0: dense_183 (Dense) ---
Weight matrix 0 shape: (2, 4)
Weight matrix 0:
[[-0.56163526 -0.01669507 -0.3067735  -0.88472843]
 [-0.54059863 -1.1826354  -1.1069899  -0.02342701]]
Weight matrix 1 shape: (4,)
Weight matrix 1:
[0.         0.9780575  0.99888575 0.        ]

--- Layer 1: dropout_134 (Dropout) ---
No weights in this layer

--- Layer 2: dense_184 (Dense) ---
Weight matrix 0 shape: (4, 1)
Weight matrix 0:
[[ 0.00385809]
 [-1.5963455 ]
 [-1.8679736 ]
 [ 0.7997173 ]]
Weight matrix 1 shape: (1,)
Weight matrix 1:
[1.126486]

First layer weights: [array([[-0.56163526, -0.01669507, -0.3067735 , -0.88472843],
       [-0.54059863, -1.1826354 , -1.1069899 , -0.02342701]],
      dtype=float32), array([0.        , 0.9780575 , 0.99888575, 0.        ], dtype=float32)]

Total number of weight arrays: 4
